configuration: Release
image: Visual Studio 2017
before_build:
  - nuget restore
deploy:
    provider: NuGet
    api_key:
      secure: v1YEQ6VGHaxKylTM0UKuIgojyELRgJlfPG/OI4LOrAAa+n74nKEOUzoXXOzKa8Qi
    artifact: bin\$(configuration)\*.nupkg/