configuration: Release
image: Visual Studio 2019
version: '2.0.{build}'
before_build:
  - nuget restore
artifacts: 
- path: 'src\**\$(configuration)\*.nupkg'
  name: NuGet
deploy:
  provider: NuGet
  name: production
  on:
    branch: master
  api_key:
    secure: 4XQI0/GHWDexH86N+VfdwaB0iTFVJgfePU9l1Cv2Nx4li2mZKz/iMDknGUu62+YP
  skip_symbols: true